services:
  api:
    container_name: vention-api
    user: "0:0"
    build:
      context: .
      dockerfile: Vention.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - CryptoSettings__PasswordPepper=${PASSWORD_PEPPER}
      - ConnectionStrings__PostgresConnection=Host=vention-postgres;Database=VentionDb;Username=${POSTGRES_SECRET_USER};Password=${POSTGRES_SECRET_PASSWORD}
      - ConnectionStrings__Redis=vention-redis:6379
      - RabbitMqSettings__Host=vention-rabbitmq
      - RabbitMqSettings__Username=${RABBIT_SECRET_USER}
      - RabbitMqSettings__Password=${RABBIT_SECRET_PASS}
      - Jwt__Secret=${JWT_SECRET}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - Jwt__AccessTokenMinutes=${JWT_EXPIRATION_MINUTES}
      - FileStorage__RootPath=${FILE_STORAGE_ROOT_PATH}
      - Gateway__SharedSecret=${GATEWAY_SHARED_SECRET}
      - Gateway__UserIdHeaderName=X-User-Id
      - Gateway__GatewaySecretHeaderName=X-Gateway-Secret
    volumes:
      - file-storage-data:/app/Storage
    networks:
      - vention-network
    depends_on:
      vention-postgres:
        condition: service_healthy
      vention-redis:
        condition: service_healthy
      vention-rabbitmq:
        condition: service_healthy

  processor:
    # container_name: vention-processor
    user: "0:0"
    build:
      context: .
      dockerfile: Vention.Processor/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ConnectionStrings__PostgresConnection=Host=vention-postgres;Database=VentionDb;Username=${POSTGRES_SECRET_USER};Password=${POSTGRES_SECRET_PASSWORD}
      - RabbitMqSettings__Host=vention-rabbitmq
      - RabbitMqSettings__Username=${RABBIT_SECRET_USER}
      - RabbitMqSettings__Password=${RABBIT_SECRET_PASS}
      - FileStorage__RootPath=${FILE_STORAGE_ROOT_PATH}
    volumes:
      - file-storage-data:/app/Storage
    networks:
      - vention-network
    depends_on:
      vention-postgres:
        condition: service_healthy
      vention-rabbitmq:
        condition: service_healthy
      api:
        condition: service_started

  api-gateway:
    container_name: vention-api-gateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - "5258:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - Jwt__Secret=${JWT_SECRET}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - Gateway__SharedSecret=${GATEWAY_SHARED_SECRET}
      - ReverseProxy__Clusters__mainApi__Destinations__destination1__Address=http://api:8080/
    networks:
      - vention-network
    depends_on:
      - api
    deploy:
      replicas: 2

  vention-postgres:
    container_name: vention-postgres
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_SECRET_USER}
      - POSTGRES_PASSWORD=${POSTGRES_SECRET_PASSWORD}
      - POSTGRES_DB=VentionDb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - vention-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_SECRET_USER} -d VentionDb"]
      interval: 5s
      timeout: 5s
      retries: 5

  vention-redis:
    container_name: vention-redis
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - vention-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  vention-rabbitmq:
    container_name: vention-rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_SECRET_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_SECRET_PASS}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - vention-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
  redis-data:
  rabbitmq-data:
  file-storage-data:


networks:
  vention-network:
    driver: bridge
